/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum150625;

import javax.swing.JOptionPane;

/**
 *
 * @author janna
 */
public class formNilai extends javax.swing.JFrame {

    /**
     * Creates new form formNilai
     */
    public formNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        txtJudul = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtKelas = new javax.swing.JLabel();
        txtMatkul = new javax.swing.JLabel();
        editNama = new javax.swing.JTextField();
        editKelas = new javax.swing.JTextField();
        editMatkul = new javax.swing.JTextField();
        txtTugas = new javax.swing.JLabel();
        txtQuiz = new javax.swing.JLabel();
        txtUTS = new javax.swing.JLabel();
        txtUAS = new javax.swing.JLabel();
        editTugas = new javax.swing.JTextField();
        editQuiz = new javax.swing.JTextField();
        editUTS = new javax.swing.JTextField();
        editUAS = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        txtNa = new javax.swing.JLabel();
        editNa = new javax.swing.JTextField();
        txtKonversi = new javax.swing.JLabel();
        editKonversi = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtJudul.setText("FORM PENILAIAN MAHASISWA");

        txtNama.setText("Nama Mahasiswa");

        txtKelas.setText("Kelas");

        txtMatkul.setText("Mata Kuliah");

        editNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNamaActionPerformed(evt);
            }
        });

        txtTugas.setText("Nilai tugas");

        txtQuiz.setText("Nilai Quiz");

        txtUTS.setText("Nilai UTS");

        txtUAS.setText("Nilai UAS");

        editQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuizActionPerformed(evt);
            }
        });

        editUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUTSActionPerformed(evt);
            }
        });

        editUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUASActionPerformed(evt);
            }
        });

        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        txtNa.setText("Nilai Akhir");

        editNa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNaActionPerformed(evt);
            }
        });

        txtKonversi.setText("Nilai Konversi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatkul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editNama)
                    .addComponent(editKelas)
                    .addComponent(editMatkul)
                    .addComponent(editTugas)
                    .addComponent(editQuiz)
                    .addComponent(editUTS)
                    .addComponent(editUAS, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGap(209, 209, 209)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editKonversi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(editNa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProses)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtJudul)
                        .addGap(262, 262, 262))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJudul)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama)
                    .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelas)
                    .addComponent(editKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatkul)
                    .addComponent(editMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProses)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTugas)
                            .addComponent(editTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuiz)
                            .addComponent(editQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUTS)
                            .addComponent(editUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUAS)
                            .addComponent(editUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNa)
                            .addComponent(editNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKonversi)
                            .addComponent(editKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void editNaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNaActionPerformed

    private void editQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editQuizActionPerformed

    private void editUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUTSActionPerformed

    private void editUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUASActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String nama = editNama.getText();
        String kelas = editKelas.getText();
        String matkul = editMatkul.getText();
        
        if(nama.isEmpty() || kelas.isEmpty() || matkul.isEmpty()){
            JOptionPane.showMessageDialog(this, "semua harus diisi","peringatan",JOptionPane.WARNING_MESSAGE);
            editNama.setText("");
            editNama.requestFocus();
        }
        if(editTugas.getText().isEmpty() || editQuiz.getText().isEmpty() || editUTS.getText().isEmpty() || editUAS.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "semua nilai harus diisi");
        }
        
        try{
            double tugas = validasiNilai(editTugas.getText(),"tugas");
            double quiz = validasiNilai(editQuiz.getText(),"quiz");
            double uts = validasiNilai(editUTS.getText(),"UTS");
            double uas = validasiNilai(editUAS.getText(),"UAS");
            
            double na = 0.15*tugas + 0.2*quiz + 0.3*uts + 0.35*uas;
            
            editNa.setText(Double.toString(na));
            
            String hasilKonversi = konversiNilai(na);
            editKonversi.setText(hasilKonversi);
        
        JOptionPane.showMessageDialog(this, "nama : "+nama+ 
                                            "\nKelas : "+matkul+
                                            "\nNilaiAkhir : "+na+
                                            "\nhasil penilaian"+JOptionPane.INFORMATION_MESSAGE);}
            catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(),"validasi nilai",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnProsesActionPerformed

    private Double validasiNilai(String input, String jenisNilai)throws Exception {
        double nilai = Double.parseDouble(input);
        if (nilai <0 || nilai >100 )
            throw new Exception (jenisNilai + "harus di antara 0-100");
        return nilai;
    }
    
     private String konversiNilai(double nilai){
         if (nilai >=80){
             return "A";
         }else if (nilai <80 && nilai >=65){
             return "B";
         }
         else if (nilai <65 && nilai >= 55){
             return "C";
         }else {
             return "D";
         }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new formNilai().setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JTextField editKelas;
    private javax.swing.JTextField editKonversi;
    private javax.swing.JTextField editMatkul;
    private javax.swing.JTextField editNa;
    private javax.swing.JTextField editNama;
    private javax.swing.JTextField editQuiz;
    private javax.swing.JTextField editTugas;
    private javax.swing.JTextField editUAS;
    private javax.swing.JTextField editUTS;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtKelas;
    private javax.swing.JLabel txtKonversi;
    private javax.swing.JLabel txtMatkul;
    private javax.swing.JLabel txtNa;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtQuiz;
    private javax.swing.JLabel txtTugas;
    private javax.swing.JLabel txtUAS;
    private javax.swing.JLabel txtUTS;
    // End of variables declaration//GEN-END:variables
}
