/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum220626;

import javax.swing.JOptionPane;

/**
 *
 * @author janna
 */
public class gajiKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form gajiKaryawan
     */
    public gajiKaryawan() {
        initComponents();
        txtGaji.setEditable(false);
        txtHon.setEditable(false);
        txtTunj.setEditable(false);
        txtPaj.setEditable(false);
        txtTot.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblGol = new javax.swing.JLabel();
        pilGol = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        rbM = new javax.swing.JRadioButton();
        lblStat = new javax.swing.JLabel();
        rbT = new javax.swing.JRadioButton();
        btnProses = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtHonor = new javax.swing.JTextField();
        txtGaji = new javax.swing.JTextField();
        txtHon = new javax.swing.JTextField();
        txtTunj = new javax.swing.JTextField();
        txtPaj = new javax.swing.JTextField();
        lblGaji = new javax.swing.JLabel();
        lblHonor = new javax.swing.JLabel();
        lblTunj = new javax.swing.JLabel();
        lblPajak = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        lblTot = new javax.swing.JLabel();
        txtNamaP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Gaji Karyawan");

        lblNama.setText("nama");

        lblGol.setText("golongan");

        pilGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pil Gol", "1", "2", "3", "4" }));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbM);
        rbM.setText("Menikah");

        lblStat.setText("Status");

        buttonGroup1.add(rbT);
        rbT.setText("Tidak Menikah");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jLabel2.setText("Jam Kerja");

        txtGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajiActionPerformed(evt);
            }
        });

        txtTunj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTunjActionPerformed(evt);
            }
        });

        txtPaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPajActionPerformed(evt);
            }
        });

        lblGaji.setText("Gaji Pokok");

        lblHonor.setText("gaji Honor");

        lblTunj.setText("tunjangan");

        lblPajak.setText("pajak");

        txtTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotActionPerformed(evt);
            }
        });

        lblTot.setText("total gaji");

        txtNamaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPActionPerformed(evt);
            }
        });

        jLabel3.setText("nama pegawai");

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKeluar)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGol)
                                    .addComponent(lblNama)
                                    .addComponent(lblStat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pilGol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNama))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbM)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnReset)
                                            .addComponent(rbT)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtHonor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPajak)
                                .addComponent(lblTot)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblTunj)
                            .addComponent(lblHonor)
                            .addComponent(lblGaji))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTot, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtHon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGaji, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTunj, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPaj, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaP))))
                .addGap(0, 115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNama)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGol)
                                    .addComponent(pilGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblGaji)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHonor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbM)
                                .addComponent(rbT)
                                .addComponent(lblTunj))
                            .addComponent(lblStat)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTunj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtHonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPajak)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnProses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTot))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(152, 152, 152))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int gol = (int)pilGol.getSelectedIndex();
        int jam = Integer.parseInt(txtHonor.getText());
        switch (gol){
            case 1: if (rbM.isSelected()){
                
                int gapok = 3000000;
                double tunjangan = gapok*0.15;
                double honor = jam*25000;
                double pajak = honor * 0.025;
                
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
                
                //JOptionPane.showMessageDialog(this, "gaji pokok: "+gapok +"\nhonor: "+honor+ "\npajak: "+pajak+"\ntunjangan menikah:"+menikah+"\ntotal gaji:"+gaji,"Golongan 1 menikah", JOptionPane.INFORMATION_MESSAGE);
            }else if (rbT.isSelected()){
                int gapok = 3000000;
                double tunjangan = 0;
                double honor = jam*25000;
                double pajak = honor * 0.025;
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
                //JOptionPane.showMessageDialog(this, "gaji pokok: "+gapok +"\nhonor: "+honor+ "\npajak: "+pajak+"\ntotal gaji:"+gaji,"Golongan 1 menikah", JOptionPane.INFORMATION_MESSAGE);
            }
            break;
            
            case 2: if (rbM.isSelected()){
                
                int gapok = 4000000;
                double tunjangan = gapok*0.15;
                double honor = jam*25000;
                double pajak = honor * 0.025;
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
            }
            else if (rbT.isSelected()){
                int gapok = 4000000;
                double tunjangan = 0;
                double honor = jam*25000;
                double pajak = honor * 0.025;
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
            }break;
            
            case 3: if (rbM.isSelected()){
                
                int gapok = 5000000;
                double tunjangan = gapok*0.15;
                double honor = jam*25000;
                double pajak = honor * 0.025;
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
            }
            else if (rbT.isSelected()){
                int gapok = 5000000;
                double tunjangan = 0;
                double honor = jam*25000;
                double pajak = honor * 0.025;
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
            } break;
            
            case 4: if (rbM.isSelected()){
                
                int gapok = 6000000;
                double tunjangan = gapok*0.15;
                double honor = jam*25000;
                double pajak = honor * 0.025;   
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
            }
            else if (rbT.isSelected()){
                int gapok = 6000000;
                double tunjangan = 0;
                double honor = jam*25000;
                double pajak = honor * 0.025;                
                double gaji = gapok + tunjangan + (honor - pajak);
                
                txtGaji.setText(Integer.toString(gapok));
                txtHon.setText(Double.toString(honor));
                txtPaj.setText(Double.toString(pajak));
                txtTunj.setText(Double.toString(tunjangan));
                txtTot.setText(Double.toString(gaji));
                txtNamaP.setText(txtNama.getText());
            }break;
        }
        
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajiActionPerformed

    private void txtTunjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTunjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTunjActionPerformed

    private void txtPajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPajActionPerformed

    private void txtNamaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNamaP.setText("");
        txtHon.setText("");
        txtHonor.setText("");
        txtGaji.setText("");
        txtTunj.setText("");
        txtTot.setText("");
        txtPaj.setText("");
        buttonGroup1.clearSelection();
        pilGol.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "apakah ingin keluar?","konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if (pil == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblGol;
    private javax.swing.JLabel lblHonor;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblStat;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblTunj;
    private javax.swing.JComboBox<String> pilGol;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbT;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtHon;
    private javax.swing.JTextField txtHonor;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaP;
    private javax.swing.JTextField txtPaj;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtTunj;
    // End of variables declaration//GEN-END:variables
}
