/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum220626;

import javax.swing.JOptionPane;

/**
 *
 * @author janna
 */
public class tiketTravel extends javax.swing.JFrame {

    /**
     * Creates new form tiketTravel
     */
    public tiketTravel() {
        initComponents();
        txtTotal.setEditable(false);
        txtTiket.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
        txtUang.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        btnGrupTujuan = new javax.swing.ButtonGroup();
        rbBkt = new javax.swing.JRadioButton();
        rbSlk = new javax.swing.JRadioButton();
        rbPar = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnHarga = new javax.swing.JButton();
        txtTiket = new javax.swing.JTextField();
        lblTiket = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtHarga = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtUang = new javax.swing.JTextField();
        lblUang = new javax.swing.JLabel();
        btnUang = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGrupTujuan.add(rbBkt);
        rbBkt.setText("Bukittinggi");

        btnGrupTujuan.add(rbSlk);
        rbSlk.setText("Solok");
        rbSlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSlkActionPerformed(evt);
            }
        });

        btnGrupTujuan.add(rbPar);
        rbPar.setText("Pariaman");
        rbPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParActionPerformed(evt);
            }
        });

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih kelas", "Ekonomi", "Bisnis", "eksekutif" }));
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });

        jLabel1.setText("Form pembelian tiket Bus Nusantara");

        jLabel2.setText("Tujuan");

        jLabel3.setText("Kelas");

        btnHarga.setText("harga 1 tiket");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        txtTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiketActionPerformed(evt);
            }
        });

        lblTiket.setText("Masukkan jumlah tiket");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        txtHarga.setText("Total Harga");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel4.setText("Diskon");

        jLabel5.setText("total Pembayaan");

        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });

        btnHitung.setText("hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangActionPerformed(evt);
            }
        });

        lblUang.setText("masukkan uang");

        btnUang.setText("hitung Uang");
        btnUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBkt)
                            .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTiket)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHarga)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHitung))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHarga)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(lblUang))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(txtDiskon)
                                            .addComponent(txtTotal)
                                            .addComponent(txtUang))
                                        .addGap(28, 28, 28)
                                        .addComponent(btnUang))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbSlk)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(rbPar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnKeluar)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBkt)
                    .addComponent(jLabel2)
                    .addComponent(rbSlk)
                    .addComponent(rbPar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHarga)
                        .addComponent(txtTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiket)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnHitung)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUang)
                    .addComponent(btnUang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSlkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSlkActionPerformed

    private void rbParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbParActionPerformed

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKelasActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        int kelas = (int)cbKelas.getSelectedIndex();
        if (!rbBkt.isSelected() && !rbSlk.isSelected()&&!rbPar.isSelected()){
            JOptionPane.showMessageDialog(this, "pilih dulu baru berangkat","pesan kesalahan",JOptionPane.ERROR_MESSAGE);
        }else if (cbKelas.getSelectedIndex()==0){
         JOptionPane.showMessageDialog(this, "kelas belum dipilih","Pesan kesalahan",JOptionPane.ERROR_MESSAGE);
        }
            
        switch(kelas){
            case 1: if(rbBkt.isSelected())
                txtTiket.setText("25000");
            else if(rbSlk.isSelected())
                txtTiket.setText("20000");
            else if(rbPar.isSelected())
                txtTiket.setText("15000");
            break;
            
            case 2: if(rbBkt.isSelected())
                txtTiket.setText("50000");
            else if(rbSlk.isSelected())
                txtTiket.setText("40000");
            else if (rbPar.isSelected())
                txtTiket.setText("30000");
            break;
            
            case 3: if (rbBkt.isSelected())
                    txtTiket.setText("80000");
            else if (rbSlk.isSelected())
                txtTiket.setText("70000");
            else if (rbPar.isSelected())
                txtTiket.setText("55000");
            break;
                    
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtTiket.setText("");
        txtJumlah.setText("");
        txtTotal.setText("");
        txtDiskon.setText("");
        txtBayar.setText("");
        txtUang.setText("");
        cbKelas.setSelectedIndex(0);
        btnGrupTujuan.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try{
        
        int jumlah = Integer.parseInt(txtJumlah.getText());
        if (jumlah <= 0){
            JOptionPane.showMessageDialog(this, "jumlah tiket tidak boleh 0","kalau 0 mau berangkat pakai apa?", JOptionPane.ERROR_MESSAGE);
        }
        double harga = Double.parseDouble(txtTiket.getText());
        double total = jumlah * harga;
        double diskon = 0;
        if (jumlah > 5 ){
            diskon = 0.1*total;
            double bayar = total-diskon;
            
            txtTotal.setText(Double.toString(total));
            txtDiskon.setText(Double.toString(diskon));
            txtBayar.setText(Double.toString(bayar));
        
        }else{
            double bayar = total;
            txtTotal.setText(Double.toString(total));
            txtDiskon.setText(Double.toString(diskon));
            txtBayar.setText(Double.toString(bayar));
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "error","jumlah harus angka dan bil genap",JOptionPane.ERROR_MESSAGE);
            txtJumlah.setText("");
            txtJumlah.requestFocus();
        }
                    
                    
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "apakah ingin keluar? ", "konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if (pil == JOptionPane.YES_OPTION){
            System.exit(0);
        } 
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiketActionPerformed

    private void txtUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangActionPerformed
        
    }//GEN-LAST:event_txtUangActionPerformed

    private void btnUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUangActionPerformed
        double pembayaran = Double.parseDouble(txtUang.getText());
        double bayar = Double.parseDouble(txtBayar.getText());
        
        if(bayar > pembayaran ){
            double uk = bayar - pembayaran;
            JOptionPane.showMessageDialog(this, "sebanyak : "+uk,"uang anda kurang",JOptionPane.INFORMATION_MESSAGE);
        }else if (pembayaran > bayar){
            double ul = pembayaran - bayar;
            JOptionPane.showMessageDialog(this, "sebanyak :"+ul,"uang anda berlebih",JOptionPane.INFORMATION_MESSAGE );
        }
       
    }//GEN-LAST:event_btnUangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiketTravel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupTujuan;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUang;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTiket;
    private javax.swing.JLabel lblUang;
    private javax.swing.JRadioButton rbBkt;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JRadioButton rbSlk;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTiket;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
