/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum290626;

import javax.swing.JOptionPane;

/**
 *
 * @author janna
 */
public class formUtama extends javax.swing.JFrame {

    /**
     * Creates new form formUtama
     */
    public formUtama() {
        initComponents();
        txtTotalMakan.setEditable(false);
        txtTotalMinum.setEditable(false);
        txtTotal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblMeja = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoMeja = new javax.swing.JTextField();
        lblTotMakan = new javax.swing.JLabel();
        txtTotalMakan = new javax.swing.JTextField();
        lblTotMinum = new javax.swing.JLabel();
        txtTotalMinum = new javax.swing.JTextField();
        btnMakan = new javax.swing.JButton();
        btnMinum = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        txtUang = new javax.swing.JTextField();
        btnUang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJudul.setText("FORM PEMESANAN MAKANAN");

        lblNama.setText("Nama Pelanggan");

        lblMeja.setText("No. Meja");

        txtNoMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoMejaActionPerformed(evt);
            }
        });

        lblTotMakan.setText("Total Harga Makanan");

        txtTotalMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMakanActionPerformed(evt);
            }
        });

        lblTotMinum.setText("Total Harga Minuman");

        txtTotalMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMinumActionPerformed(evt);
            }
        });

        btnMakan.setText("Menu Makanan");
        btnMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakanActionPerformed(evt);
            }
        });

        btnMinum.setText("Menu Minuman");
        btnMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumActionPerformed(evt);
            }
        });

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnTotal.setText("Total Harga");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnUang.setText("masukkan uang");
        btnUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblMeja)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinum)
                            .addComponent(btnMakan))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnUang))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(txtNoMeja))
                            .addComponent(btnReset))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotMakan)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalMakan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotMinum)
                                    .addComponent(btnTotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnKeluar)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalMinum, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(txtTotal)
                                    .addComponent(txtUang))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotMakan)
                    .addComponent(txtTotalMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeja)
                    .addComponent(txtNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotMinum)
                    .addComponent(txtTotalMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMakan)
                        .addComponent(btnUang))
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoMejaActionPerformed

    private void txtTotalMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMakanActionPerformed

    private void btnMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumActionPerformed
        menuMinuman frm = new menuMinuman(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMinumActionPerformed

    private void btnMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakanActionPerformed
        menuMakanan frm  = new menuMakanan(this);
        frm.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnMakanActionPerformed

    private void txtTotalMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMinumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMinumActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double a = Double.parseDouble(txtTotalMakan.getText());
        double b = Double.parseDouble(txtTotalMinum.getText());
        
        double t = a+b;
        txtTotal.setText(Double.toString(t));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUangActionPerformed
        double bayar = Double.parseDouble(txtTotal.getText());
        double uang = Double.parseDouble(txtUang.getText());
        String nama = txtNama.getText();
        String meja = txtNoMeja.getText();
        
        if (uang > bayar){
            double kembalian = uang - bayar;
            JOptionPane.showMessageDialog(this,"kembalian uang anda sebanyak: "+kembalian+"\nPembayaran atas nama: "+nama+
                    "\ndengan nomor meja: "+meja+
                    "\nsukses, terimakasih sudah mampir di resto kami :D","kembalian" , JOptionPane.INFORMATION_MESSAGE);
        }else if (bayar>uang){
            double kurang = bayar-uang;
            JOptionPane.showMessageDialog(this,"uang anda kurang sebanyak: "+kurang,"kekurangan" , JOptionPane.INFORMATION_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(this,"Pembayaran atas nama: "+nama+
                    "\ndengan nomor meja: "+meja+
                    "\nsukses, terimakasih sudah mampir di resto kami :D","Terimakasih :D" , JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_btnUangActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNoMeja.setText("");
        txtTotalMakan.setText("");
        txtTotalMinum.setText("");
        txtTotal.setText("");
        txtUang.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    public void setTotalMakanan (String nilai){
        txtTotalMakan.setText(nilai);
    }
    
    public void setTotalMinuman (String nilai){
        txtTotalMinum.setText(nilai);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMakan;
    private javax.swing.JButton btnMinum;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnUang;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblMeja;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTotMakan;
    private javax.swing.JLabel lblTotMinum;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoMeja;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalMakan;
    private javax.swing.JTextField txtTotalMinum;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
