/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum290626;

/**
 *
 * @author janna
 */
public class menuMinuman extends javax.swing.JFrame {

    /**
     * Creates new form menuMinuman
     */
    private formUtama utama;
    
    public menuMinuman() {
        initComponents();
        txtHargaTeh.setEditable(false);
        txtHargaJeruk.setEditable(false);
        txtHargaAir.setEditable(false);
        txtTotalTeh.setEditable(false);
        txtTotalJeruk.setEditable(false);
        txtTotalAir.setEditable(false);
        txtTotal.setEditable(false);
        
    }

    public menuMinuman(formUtama utama) {
        this.utama = utama;
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkEsteh = new javax.swing.JCheckBox();
        chkEsjeruk = new javax.swing.JCheckBox();
        chkAir = new javax.swing.JCheckBox();
        txtHargaTeh = new javax.swing.JTextField();
        txtHargaJeruk = new javax.swing.JTextField();
        txtHargaAir = new javax.swing.JTextField();
        cbTeh = new javax.swing.JComboBox<>();
        cbJeruk = new javax.swing.JComboBox<>();
        cbAir = new javax.swing.JComboBox<>();
        txtTotalTeh = new javax.swing.JTextField();
        txtTotalJeruk = new javax.swing.JTextField();
        txtTotalAir = new javax.swing.JTextField();
        lblhargaAir = new javax.swing.JLabel();
        lblHargaJeruk = new javax.swing.JLabel();
        lblHargaTeh = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Menu Minuman");

        chkEsteh.setText("es Teh");
        chkEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstehActionPerformed(evt);
            }
        });

        chkEsjeruk.setText("es Jeruk");
        chkEsjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsjerukActionPerformed(evt);
            }
        });

        chkAir.setText("air mineral");
        chkAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAirActionPerformed(evt);
            }
        });

        txtHargaTeh.setText("0");

        txtHargaJeruk.setText("0");
        txtHargaJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJerukActionPerformed(evt);
            }
        });

        txtHargaAir.setText("0");

        cbTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        cbJeruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJerukActionPerformed(evt);
            }
        });

        cbAir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAirActionPerformed(evt);
            }
        });

        txtTotalTeh.setText("0");

        txtTotalJeruk.setText("0");
        txtTotalJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalJerukActionPerformed(evt);
            }
        });

        txtTotalAir.setText("0");

        lblhargaAir.setText("harga");

        lblHargaJeruk.setText("harga");

        lblHargaTeh.setText("harga");

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnKembali.setText("kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEsteh)
                    .addComponent(chkEsjeruk)
                    .addComponent(chkAir))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHargaTeh, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtHargaJeruk)
                    .addComponent(txtHargaAir))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblhargaAir)
                                    .addComponent(lblHargaJeruk)
                                    .addComponent(lblHargaTeh))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnTotal)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtTotalTeh)
                            .addComponent(txtTotalJeruk)
                            .addComponent(txtTotalAir, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEsteh)
                            .addComponent(txtHargaTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEsjeruk)
                            .addComponent(txtHargaJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHargaJeruk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkAir)
                            .addComponent(txtHargaAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblhargaAir)))
                    .addComponent(lblHargaTeh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstehActionPerformed
        txtHargaTeh.setText("5000");
    }//GEN-LAST:event_chkEstehActionPerformed

    private void txtHargaJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJerukActionPerformed

    private void txtTotalJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalJerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalJerukActionPerformed

    private void chkEsjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsjerukActionPerformed
        txtHargaJeruk.setText("7000");
        
    }//GEN-LAST:event_chkEsjerukActionPerformed

    private void chkAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAirActionPerformed
        txtHargaAir.setText("3000");
    }//GEN-LAST:event_chkAirActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        int jumlah = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtHargaTeh.getText());
        double total = jumlah*harga;
        
        txtTotalTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void cbJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJerukActionPerformed
        int jumlah = (int)cbJeruk.getSelectedIndex();
        double harga = Double.parseDouble(txtHargaJeruk.getText());
        double total = jumlah*harga;
        
        txtTotalJeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbJerukActionPerformed

    private void cbAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirActionPerformed
        int jumlah = (int)cbAir.getSelectedIndex();
        double harga = Double.parseDouble(txtHargaAir.getText());
        double total = jumlah*harga;
        
        txtTotalAir.setText(Double.toString(total));
    }//GEN-LAST:event_cbAirActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double a = Double.parseDouble(txtTotalTeh.getText());
        double b = Double.parseDouble(txtTotalJeruk.getText());
        double c = Double.parseDouble(txtTotalAir.getText());
        
        double t = a+b+c;
        txtTotal.setText(Double.toString(t));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbAir;
    private javax.swing.JComboBox<String> cbJeruk;
    private javax.swing.JComboBox<String> cbTeh;
    private javax.swing.JCheckBox chkAir;
    private javax.swing.JCheckBox chkEsjeruk;
    private javax.swing.JCheckBox chkEsteh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHargaJeruk;
    private javax.swing.JLabel lblHargaTeh;
    private javax.swing.JLabel lblhargaAir;
    private javax.swing.JTextField txtHargaAir;
    private javax.swing.JTextField txtHargaJeruk;
    private javax.swing.JTextField txtHargaTeh;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAir;
    private javax.swing.JTextField txtTotalJeruk;
    private javax.swing.JTextField txtTotalTeh;
    // End of variables declaration//GEN-END:variables
}
