/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum290626;

import java.awt.HeadlessException;

/**
 *
 * @author janna
 */
public class menuMakanan extends javax.swing.JFrame {

    /**
     * Creates new form menuMakanan
     */
    
    private formUtama utama;
    
    public menuMakanan() {
        initComponents();
        txtHargaNasgor.setEditable(false);
        txtHargaMiegor.setEditable(false);
        txtHargaMiebus.setEditable(false);
        txtTotalMiegor.setEditable(false);
        txtTotalNasgor.setEditable(false);
        txtTotalMiebus.setEditable(false);
        txtTotal.setEditable(false);
        
    }

    public menuMakanan(formUtama utama) throws HeadlessException {
        this.utama = utama;
        initComponents();
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkNasgor = new javax.swing.JCheckBox();
        chkMieGor = new javax.swing.JCheckBox();
        chkMieRebus = new javax.swing.JCheckBox();
        txtHargaNasgor = new javax.swing.JTextField();
        txtHargaMiegor = new javax.swing.JTextField();
        txtHargaMiebus = new javax.swing.JTextField();
        cbJumlahNasgor = new javax.swing.JComboBox<>();
        cbJumlahMiegor = new javax.swing.JComboBox<>();
        cbJumlahMiebus = new javax.swing.JComboBox<>();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalMiegor = new javax.swing.JTextField();
        txtTotalMiebus = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pilih Menu Makanan");

        chkNasgor.setText("Nasi Goreng");
        chkNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasgorActionPerformed(evt);
            }
        });

        chkMieGor.setText("Mie Goreng");
        chkMieGor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieGorActionPerformed(evt);
            }
        });

        chkMieRebus.setText("Mie Rebus");
        chkMieRebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieRebusActionPerformed(evt);
            }
        });

        txtHargaNasgor.setText("0");

        txtHargaMiegor.setText("0");
        txtHargaMiegor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaMiegorActionPerformed(evt);
            }
        });

        txtHargaMiebus.setText("0");

        cbJumlahNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJumlahNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJumlahNasgorActionPerformed(evt);
            }
        });

        cbJumlahMiegor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJumlahMiegor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJumlahMiegorActionPerformed(evt);
            }
        });

        cbJumlahMiebus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " ", " " }));
        cbJumlahMiebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJumlahMiebusActionPerformed(evt);
            }
        });

        txtTotalNasgor.setText("0");

        txtTotalMiegor.setText("0");
        txtTotalMiegor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMiegorActionPerformed(evt);
            }
        });

        txtTotalMiebus.setText("0");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnKembali.setText("kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotal.setText("TOTAL");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNasgor)
                            .addComponent(chkMieGor)
                            .addComponent(chkMieRebus))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHargaMiegor)
                            .addComponent(txtHargaMiebus)
                            .addComponent(txtHargaNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnKembali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbJumlahNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbJumlahMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbJumlahMiebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnTotal))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalNasgor)
                                    .addComponent(txtTotalMiegor)
                                    .addComponent(txtTotalMiebus)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkNasgor)
                            .addComponent(txtHargaNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkMieGor)
                            .addComponent(txtHargaMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMieRebus)
                            .addComponent(txtHargaMiebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJumlahNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJumlahMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMiegor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJumlahMiebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMiebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotal))))
                .addGap(84, 84, 84)
                .addComponent(btnKembali)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasgorActionPerformed
        txtHargaNasgor.setText("15000");
    }//GEN-LAST:event_chkNasgorActionPerformed

    private void chkMieGorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieGorActionPerformed
        txtHargaMiegor.setText("12000");
    }//GEN-LAST:event_chkMieGorActionPerformed

    private void txtHargaMiegorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaMiegorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaMiegorActionPerformed

    private void txtTotalMiegorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMiegorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMiegorActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
       
    }//GEN-LAST:event_txtTotalActionPerformed

    private void chkMieRebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieRebusActionPerformed
        txtHargaMiebus.setText("12000");
    }//GEN-LAST:event_chkMieRebusActionPerformed

    private void cbJumlahNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJumlahNasgorActionPerformed
        int jumlah = (int)cbJumlahNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtHargaNasgor.getText());
        double total = jumlah*harga;
        txtTotalNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbJumlahNasgorActionPerformed

    private void cbJumlahMiegorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJumlahMiegorActionPerformed
        int jumlah =(int) cbJumlahMiegor.getSelectedIndex();
        double harga = Double.parseDouble(txtHargaMiegor.getText());
        double total = jumlah*harga;
        txtTotalMiegor.setText(Double.toString(total));
    }//GEN-LAST:event_cbJumlahMiegorActionPerformed

    private void cbJumlahMiebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJumlahMiebusActionPerformed
        int jumlah =(int) cbJumlahMiebus.getSelectedIndex();
        double harga = Double.parseDouble(txtHargaMiebus.getText());
        double total = jumlah*harga;
        txtTotalMiebus.setText(Double.toString(total));
    }//GEN-LAST:event_cbJumlahMiebusActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double total1 = Double.parseDouble(txtTotalNasgor.getText());
        double total2 = Double.parseDouble(txtTotalMiegor.getText());
        double total3 = Double.parseDouble(txtTotalMiebus.getText());
        
        double total = total1 + total2 + total3;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    String total = txtTotal.getText();
    utama.setTotalMakanan(total);
    this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbJumlahMiebus;
    private javax.swing.JComboBox<String> cbJumlahMiegor;
    private javax.swing.JComboBox<String> cbJumlahNasgor;
    private javax.swing.JCheckBox chkMieGor;
    private javax.swing.JCheckBox chkMieRebus;
    private javax.swing.JCheckBox chkNasgor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtHargaMiebus;
    private javax.swing.JTextField txtHargaMiegor;
    private javax.swing.JTextField txtHargaNasgor;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalMiebus;
    private javax.swing.JTextField txtTotalMiegor;
    private javax.swing.JTextField txtTotalNasgor;
    // End of variables declaration//GEN-END:variables
}
